const mongoose = require("mongoose");
const Adminission = mongoose.Schema({
  classApplied: { type: String, require: true },
  email: { type: String, require: true },
  namePupil: { type: String, require: true },
  gender: { type: String, require: true },
  dob: { type: Date, require: true },
  placedob: { type: String, require: true },
  nationality: { type: String, require: true },
  religion: { type: String, require: true },
  fName: { type: String, require: true },
  fOccupation: { type: String, require: true },
  fMobileNo: { type: String, require: true },
  fOffNo: { type: String, require: true },
  mName: { type: String, require: true },
  mOccupation: { type: String, require: true },
  mMobileNo: { type: String, require: true },
  mOffNo: { type: String, require: true },
  pFAddress: { type: String, require: true },
  gName: { type: String, require: true },
  fAddress: { type: String, require: true },
  allContactNo: { type: String, require: true },
  bloodGroup: { type: String, require: true },
  vaccinationsTaken: { type: String, require: true },
  anyAllergies: { type: String, require: true },
  place: { type: String, require: true },
  formDate: { type: Date, default: Date.now },
  accepted: { type: Boolean, default: null },
});
module.exports = mongoose.model("Adminission", Adminission);
